server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Firdavs-Haydarov/spring-cloud-config
          username: Firdavs-Haydarov
          pasword: Xenomania1982
          search-paths:
           - '*service'



